from pydantic import BaseModel,Field

class PatientData(BaseModel):
    radius_mean: float = Field(ge=0)
    texture_mean: float = Field(ge=0)
    perimeter_mean: float = Field(ge=0)
    area_mean: float = Field(ge=0)
    smoothness_mean: float = Field(ge=0)
    compactness_mean: float = Field(ge=0)
    concavity_mean: float = Field(ge=0) 
    concave_points_mean: float = Field(ge=0)
    symmetry_mean: float = Field(ge=0)
    radius_se: float = Field(ge=0)
    perimeter_se: float = Field(ge=0)
    area_se: float = Field(ge=0)
    compactness_se: float = Field(ge=0)
    concavity_se: float = Field(ge=0)
    concave_points_se: float = Field(ge=0)
    radius_worst: float = Field(ge=0)
    texture_worst: float = Field(ge=0)
    perimeter_worst: float = Field(ge=0)
    area_worst: float = Field(ge=0)
    smoothness_worst: float = Field(ge=0)
    compactness_worst: float = Field(ge=0)
    concavity_worst: float = Field(ge=0)
    concave_points_worst: float = Field(ge=0)
    symmetry_worst: float = Field(ge=0)
    fractal_dimension_worst: float = Field(ge=0)  